### PR TITLE
Fix TypeError: object of type 'ShuffleDataset' has no len()

### PR DESCRIPTION
**Pull request by D3mianGianoz**
This simple pull request stems from a small type bug encountered during my learning at https://learn.microsoft.com/.
I take this opportunity to thank MS and its team for the nice material.
I have no previous experience of contributing to open source projects, I'm trying to be compliant with the code of conduct. 

On the sandboxes kindly granted by Microsoft, the current version of tensorflow is 2.2, which is why I chose to use the https://www.tensorflow.org/versions/r2.2/api_docs/python/tf/data/experimental/cardinality method.

In later versions it has been integrated into the parent class tf.data.Dataset

### CODE REVIEW

**Comment by D3mianGianoz** [comment]
@microsoft-github-policy-service agree

**Comment by D3mianGianoz** [comment]
Any luck of getting this an approval? @shwars

**Comment by shwars** [comment]
> Any luck of getting this an approval? @shwars

I am no longer with Microsoft, so bringing this to the attention of @bstollnitz

**Comment by bstollnitz** [comment]
Hi, and thanks for reporting this issue and providing a fix! This has been fixed a while ago, before I was made aware of your fix. Let me know if the new code that is publicly available doesn't work for you. Once again, thank you so much!

**Comment by D3mianGianoz** [comment]
Hi @bstollnitz, what do you mean by "publicly available"? The one hosted on MS?
Anyway I'll be happy to close the PR if merge is not allowed  :)

**Pull request closed without merging**
